baseURL = 'https://1090MHz.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'AltitudeDark'

# Enable section-based menus
sectionPagesMenu = "main"

# Optional: Configure additional settings
[params]
  # Add any custom parameters here
