[build]
  command = "npm ci --prefix themes/AltitudeDark --ignore-scripts && npm run build --prefix themes/AltitudeDark && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.145.0"